service: activity-log
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    SECRET: ${env:SECRET}

functions:
  logActivity:
    handler: src/handler.logActivity
    events:
      - httpApi:
          path: /
          method: POST

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 1337
